/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-low": "#f3f3f3",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        surface: "#f9f9f9",
        background: "#f9f9f9",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1dfdf",
        "on-secondary-container": "#626262",
        "on-surface": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "on-background": "#1b1b1b",
        "outline-variant": "#cfc4c5",
        outline: "#7e7576",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "map-accent": "#2196F3",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
